const {JSDOM}=require('jsdom'),fs=require('fs');
const dom=new JSDOM(fs.readFileSync('Browse2.html','utf8'),{runScripts:'dangerously'});
const d=dom.window.document,q=d.getElementById('q'),s=d.getElementById('status');
const vis=()=>[...d.querySelectorAll('article')].filter(a=>!a.hidden).map(a=>a.querySelector('h2').textContent);
const run=v=>{q.value=v;q.dispatchEvent(new dom.window.Event('input'));return {status:s.textContent,visible:vis()};};
const t=(label,v,fn)=>{const r=run(v);const ok=fn(r);console.log((ok?'PASS':'FAIL')+'  '+label+'   -> '+r.status+'  '+JSON.stringify(r.visible));};
console.log('initial status:', s.textContent, JSON.stringify(vis()),'\n');
t('empty query shows all','',r=>r.visible.length===4);
t('single word','indemnity',r=>r.visible.length===3);
t('two words AND','indemnity cap',r=>r.visible.length===2);
t('case-insensitive','INDEMNITY',r=>r.visible.length===3);
t('no match','frustration',r=>r.visible.length===0);
t('matches the metadata line too','Negotiation',r=>r.visible.length===1);
console.log('\n--- searches a lawyer would actually try ---');
t('phrase search (quoted) fails','"hold harmless"',r=>r.visible.length>0);
t('hyphenated term','one-way',r=>r.visible.length===1);
t('plural of a stored singular','indemnities',r=>r.visible.length>0);
t('stem: liability vs liabilities','liabilities',r=>r.visible.length>0);
t('typo tolerance','indemnty',r=>r.visible.length>0);
t('possessive apostrophe',"supplier's",r=>r.visible.length>0);
t('substring hits mid-word (false positive)','cap',r=>r.visible.length===2);
